### ISSUE TITLE
Can't play by genre

### ISSUE THREAD

**Issue by inonio** [pavoni/pyroon#25] opened 2021-01-19 00:34 UTC
when calling play_media with a genre & subgenre, pyroon errors out:
e.g `Genres/Jazz/Cool`
```
  File "/usr/local/lib/python3.8/site-packages/roonapi/roonapi.py", line 521, in play_media
    total_count = self.browse_browse(opts)["list"]["count"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by pavoni** [comment] 2021-01-29 17:17
I just tried 
```
items = roonapi.play_media(
    output_id, ["Genres", "Jazz", "Cool"]
)
```

It is possible you have no content there (it's quite possible I'm not handling that!)

Hard to test on my setup - because Qobuz has some of everything!

**Comment by pavoni** [comment] 2021-02-08 14:30
Will close since I can't reproduce, but please re-open if you have more details.

**Comment by pavoni** [comment] 2021-02-10 10:38
This looks similar https://github.com/home-assistant/core/issues/46318

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 630, in async_play_media
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/roon/media_player.py", line 482, in play_media
    self._server.roonapi.play_id(self.zone_id, media_id)
  File "/usr/local/lib/python3.8/site-packages/roonapi/roonapi.py", line 580, in play_id
    if header_result["list"]["level"] == 0:
TypeError: string indices must be integers
```

**Comment by pavoni** [comment] 2021-02-10 12:45
Closing again - the log above related to using the media_browser in home assistant.

This PR will improve the error logging https://github.com/pavoni/pyroon/pull/32

**Closed by pavoni** 2021-02-10 12:45 UTC
